spring:
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB

server:
  port: 8081

logging:
  file:
    name: C:\\Users\\SSAFY\\Desktop\\log\\ssafybank.log
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web.socket: trace
