spring:
  profiles: # profiles ??
    active: dev # ?? ??? ?? ? default ?? ?
  # jpa??
  jpa:
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true # ???? ??? ??? ??? -> ??????? ? ? ??? ???
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB

server:
  port: 8081

# ?? ?? ??
logging:
  level:
    # hibernate ? ??? ?? ??? debug??? ??
    # jpa hibernate? ???? sql? ??? ??? ???? ?? ??
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web.socket: trace
